'use client';
import {useState} from 'react';
import {Users,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
export type Member={account_id:string,email:string,user_id:string|null};
export default function Sharing({account,members,refresh}:{account:{id:string,name:string},members:Member[],refresh:()=>Promise<void>}){const [open,setOpen]=useState(false),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function save(action:string,value=email){setBusy(true);setError('');try{const r=await fetch('/api/sharing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,email:value,account_id:account.id})});const j:any=await r.json();if(!r.ok)throw Error(j.error);await refresh();setEmail('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
return <><Button variant="ghost" className="share-button" onClick={()=>setOpen(true)}><Users size={15}/> Condividi</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="form-dialog"><DialogTitle>Condividi {account.name}</DialogTitle><DialogDescription>Chi aggiungi potrà vedere e registrare i movimenti di questo conto. Gli altri tuoi conti rimangono privati.</DialogDescription><form onSubmit={e=>{e.preventDefault();save('add');}}><label>Email del partecipante<Input type="email" required maxLength={254} placeholder="Email del suo account ChatGPT" value={email} onChange={e=>setEmail(e.target.value)}/></label><Button className="primary save" disabled={busy}>{busy?'Salvataggio…':'Aggiungi partecipante'}</Button></form><div className="sharing-note"><b>Due passaggi per accedere</b><p>1. Aggiungi qui il partecipante al conto.</p><p>2. Autorizzalo anche ad aprire l’app privata Tasca. Per attivare l’accesso, comunica la sua email nella conversazione con cui hai creato Tasca.</p><p>Questo pulsante non invia email. Chi è già autorizzato all’app ritroverà il conto dopo l’accesso o il prossimo aggiornamento.</p></div>{members.length>0&&<ul className="member-list">{members.map(m=><li key={m.email}><div><b>{m.email}</b><span>{m.user_id?'Accesso al conto attivato':'In attesa del primo accesso'}</span></div><AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" disabled={busy} aria-label={`Rimuovi ${m.email}`}><Trash2 size={16}/></Button></AlertDialogTrigger><AlertDialogContent><AlertDialogTitle>Rimuovere il partecipante?</AlertDialogTitle><AlertDialogDescription>Non potrà più accedere a questo conto. I movimenti già registrati rimarranno nel rendiconto.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Annulla</AlertDialogCancel><AlertDialogAction onClick={()=>save('remove',m.email)}>Rimuovi</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></li>)}</ul>}{error&&<p className="error" role="alert">{error}</p>}</DialogContent></Dialog></>;
}
