import { integer, sqliteTable, text, primaryKey, index } from 'drizzle-orm/sqlite-core';
export const movements=sqliteTable('movements',{id:text('id').primaryKey(),type:text('type').notNull(),amount:integer('amount').notNull(),category:text('category').notNull(),description:text('description').notNull(),date:text('date').notNull(),accountId:text('account_id'),toAccountId:text('to_account_id'),ownerId:text('owner_id'),author:text('author'),updatedBy:text('updated_by')},t=>[index('idx_movements_account_date').on(t.accountId,t.date),index('idx_movements_to_account').on(t.toAccountId),index('idx_movements_owner').on(t.ownerId)]);
export const budgets=sqliteTable('budgets',{month:text('month').primaryKey(),amount:integer('amount').notNull()});
export const accounts=sqliteTable('accounts',{id:text('id').primaryKey(),name:text('name').notNull(),opening:integer('opening').notNull(),openingDate:text('opening_date').notNull(),ownerId:text('owner_id')},t=>[index('idx_accounts_owner').on(t.ownerId)]);
export const recurring=sqliteTable('recurring',{id:text('id').primaryKey(),type:text('type').notNull(),amount:integer('amount').notNull(),category:text('category').notNull(),description:text('description').notNull(),accountId:text('account_id').notNull(),startDate:text('start_date').notNull(),endDate:text('end_date'),active:integer('active').notNull().default(1),ownerId:text('owner_id')},t=>[index('idx_recurring_account').on(t.accountId)]);
export const occurrences=sqliteTable('occurrences',{id:text('id').primaryKey(),recurringId:text('recurring_id').notNull(),date:text('date').notNull()},t=>[index('idx_occurrences_recurring').on(t.recurringId)]);

export const siteState=sqliteTable('site_state',{key:text('key').primaryKey(),value:text('value').notNull()});
export const personalBudgets=sqliteTable('personal_budgets',{ownerId:text('owner_id').notNull(),month:text('month').notNull(),amount:integer('amount').notNull()},t=>[primaryKey({columns:[t.ownerId,t.month]})]);
export const accountMembers=sqliteTable('account_members',{accountId:text('account_id').notNull(),email:text('email').notNull(),userId:text('user_id')},t=>[primaryKey({columns:[t.accountId,t.email]}),index('idx_members_user').on(t.userId),index('idx_members_email').on(t.email)]);
