import {database,check,cents,id,validateMovement,mutationAllowed,failure} from '@/lib/finance-db';
import {identity,visibleAccounts,permittedAccount,permittedMovement,AccessError} from '@/lib/access';
export async function GET(req:Request){try{const u=await identity(req),db=database(),accounts=await visibleAccounts(u),ids=new Set(accounts.map(a=>a.id));
 const [m,b,r,o,members]=await Promise.all([
 db.prepare('SELECT * FROM movements WHERE (account_id IS NULL AND owner_id=?) OR account_id IN (SELECT a.id FROM accounts a WHERE a.owner_id=? OR EXISTS(SELECT 1 FROM account_members s WHERE s.account_id=a.id AND s.user_id=?)) OR to_account_id IN (SELECT a.id FROM accounts a WHERE a.owner_id=? OR EXISTS(SELECT 1 FROM account_members s WHERE s.account_id=a.id AND s.user_id=?)) ORDER BY date DESC,id DESC').bind(u.id,u.id,u.id,u.id,u.id).all<any>(),
 db.prepare('SELECT month,amount FROM personal_budgets WHERE owner_id=?').bind(u.id).all(),
 db.prepare('SELECT r.* FROM recurring r WHERE account_id IN (SELECT a.id FROM accounts a WHERE a.owner_id=? OR EXISTS(SELECT 1 FROM account_members s WHERE s.account_id=a.id AND s.user_id=?)) ORDER BY description').bind(u.id,u.id).all<any>(),
 db.prepare('SELECT o.* FROM occurrences o JOIN recurring r ON r.id=o.recurring_id WHERE r.account_id IN (SELECT a.id FROM accounts a WHERE a.owner_id=? OR EXISTS(SELECT 1 FROM account_members s WHERE s.account_id=a.id AND s.user_id=?))').bind(u.id,u.id).all(),
 db.prepare('SELECT m.account_id,m.email,m.user_id FROM account_members m JOIN accounts a ON a.id=m.account_id WHERE a.owner_id=?').bind(u.id).all<any>()]);
 const counts=await db.prepare('SELECT account_id,COUNT(*) AS count FROM account_members GROUP BY account_id').all<any>();
 return Response.json({user:u,movements:m.results.map(x=>({...x,account_id:ids.has(x.account_id)?x.account_id:null,to_account_id:ids.has(x.to_account_id)?x.to_account_id:null,can_edit:(!x.account_id||ids.has(x.account_id))&&(!x.to_account_id||ids.has(x.to_account_id))})),budgets:b.results,accounts:accounts.map(a=>({...a,can_share:a.owner_id===u.id,shared:counts.results.some(c=>c.account_id===a.id&&c.count>0)})),recurring:r.results,occurrences:o.results,members:members.results},{headers:{'Cache-Control':'no-store'}});
 }catch(e){return failure(e);}}
export async function POST(req:Request){try{if(!mutationAllowed(req))return new Response(null,{status:403});const u=await identity(req),v:any=await req.json();check(v&&typeof v==='object');const db=database();
 if(v.action==='budget'){check(/^\d{4}-(0[1-9]|1[0-2])$/.test(v.month));cents(v.amount,true);check(v.amount>=0);await db.prepare('INSERT INTO personal_budgets(owner_id,month,amount) VALUES(?,?,?) ON CONFLICT(owner_id,month) DO UPDATE SET amount=excluded.amount').bind(u.id,v.month,v.amount).run();}
 else if(v.action==='delete'){id(v.id);const old=await db.prepare('SELECT * FROM movements WHERE id=?').bind(v.id).first<any>();if(!old)throw new AccessError('Movimento non disponibile.');await permittedMovement(u,old);await db.prepare('DELETE FROM movements WHERE id=?').bind(v.id).run();}
 else {v.id=v.id||crypto.randomUUID();if(v.account_id)await permittedAccount(u,v.account_id);if(v.type==='transfer')await permittedAccount(u,v.to_account_id);await validateMovement(v);const old=await db.prepare('SELECT * FROM movements WHERE id=?').bind(v.id).first<any>();if(old){await permittedMovement(u,old);if(old.owner_id!==u.id)check(old.account_id===v.account_id&&old.to_account_id===(v.to_account_id||null),'Non puoi spostare su un altro conto un movimento registrato da un’altra persona.');}if(v.account_id)await permittedAccount(u,v.account_id);if(v.type==='transfer')await permittedAccount(u,v.to_account_id);
 await db.prepare('INSERT INTO movements(id,type,amount,category,description,date,account_id,to_account_id,owner_id,author,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET type=excluded.type,amount=excluded.amount,category=excluded.category,description=excluded.description,date=excluded.date,account_id=excluded.account_id,to_account_id=excluded.to_account_id,updated_by=excluded.updated_by WHERE ?=1').bind(v.id,v.type,v.amount,v.category,v.description.trim(),v.date,v.account_id||null,v.type==='transfer'?v.to_account_id:null,u.id,u.name,u.name,old?1:0).run();}
 return Response.json({ok:true});}catch(e){return failure(e);}}
